print("Hi, my name is RudeAI. \n I'd like to ask you a few questions.")
name= input("First, what is your name?:")
print("Wow", name, "!? That name kind of sucks")
age = int(input("How old are you?:"))
print("Sheesh", age, ", really? That's rough man")
fun= input("Okay well what do you do for fun?:")
print("Wow you must be pretty boring if you", fun," for fun")
music=input("What kind of music do you like?:")
print("What!?", music,"!? You honestly are just getting worse and worse")
siblings=int(input("How many siblings do you have?:"))
print("wow, your parents must have hated having", siblings, "of you in the house")
job=input("What do you want to be when you grow up?:")
print("Terrible choice. Why would anyone want to be", job, "!?\nSo", name, ", you're", age,"...\nYou like to", fun, "and listen to", music, "...\nGood luck becoming a", job, ".\nI'm only kidding", name, ".")
